
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";



import { StackHandlerRoutes, LoginRedirect } from "app/auth";


import AIChatWorkspace from "./pages/AIChatWorkspace.tsx";
import ApiScraperPage from "./pages/ApiScraperPage.tsx";
import App from "./pages/App.tsx";
import GitHub from "./pages/GitHub.tsx";
import InstalledPackagesPage from "./pages/InstalledPackagesPage.tsx";
import Projects from "./pages/Projects.tsx";
import TestAgentTools from "./pages/TestAgentTools.tsx";
import TestPreviewBuild from "./pages/TestPreviewBuild.tsx";

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/ai-chat-workspace", element: <AIChatWorkspace /> },
	{ path: "/aichatworkspace", element: <AIChatWorkspace /> },
	{ path: "/api-scraper-page", element: <ApiScraperPage /> },
	{ path: "/apiscraperpage", element: <ApiScraperPage /> },
	{ path: "/", element: <App /> },
	{ path: "/git-hub", element: <GitHub /> },
	{ path: "/github", element: <GitHub /> },
	{ path: "/installed-packages-page", element: <InstalledPackagesPage /> },
	{ path: "/installedpackagespage", element: <InstalledPackagesPage /> },
	{ path: "/projects", element: <Projects /> },
	{ path: "/test-agent-tools", element: <TestAgentTools /> },
	{ path: "/testagenttools", element: <TestAgentTools /> },
	{ path: "/test-preview-build", element: <TestPreviewBuild /> },
	{ path: "/testpreviewbuild", element: <TestPreviewBuild /> },

];
